<?php
/**
 * AccountUsage
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.13
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * AccountUsage Class Doc Comment
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AccountUsage implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'AccountUsage';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'requests' => 'int',
        'quota' => 'int',
        'hard_limit' => 'int',
        'window_start' => '\DateTime',
        'window_end' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'requests' => 'int64',
        'quota' => 'int64',
        'hard_limit' => 'int64',
        'window_start' => 'date-time',
        'window_end' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'requests' => false,
        'quota' => false,
        'hard_limit' => true,
        'window_start' => false,
        'window_end' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'requests' => 'requests',
        'quota' => 'quota',
        'hard_limit' => 'hard_limit',
        'window_start' => 'window_start',
        'window_end' => 'window_end'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'requests' => 'setRequests',
        'quota' => 'setQuota',
        'hard_limit' => 'setHardLimit',
        'window_start' => 'setWindowStart',
        'window_end' => 'setWindowEnd'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'requests' => 'getRequests',
        'quota' => 'getQuota',
        'hard_limit' => 'getHardLimit',
        'window_start' => 'getWindowStart',
        'window_end' => 'getWindowEnd'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('requests', $data ?? [], null);
        $this->setIfExists('quota', $data ?? [], null);
        $this->setIfExists('hard_limit', $data ?? [], null);
        $this->setIfExists('window_start', $data ?? [], null);
        $this->setIfExists('window_end', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['requests'] === null) {
            $invalidProperties[] = "'requests' can't be null";
        }
        if ($this->container['quota'] === null) {
            $invalidProperties[] = "'quota' can't be null";
        }
        if ($this->container['hard_limit'] === null && !$this->isNullableSetToNull('hard_limit')) {
            $invalidProperties[] = "'hard_limit' is required";
        }
        if ($this->container['window_start'] === null) {
            $invalidProperties[] = "'window_start' can't be null";
        }
        if ($this->container['window_end'] === null) {
            $invalidProperties[] = "'window_end' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets requests
     *
     * @return int
     */
    public function getRequests(): int
    {
        return $this->container['requests'];
    }

    /**
     * Sets requests
     *
     * @param int $requests Requests counted in the current window. The same number the lookup API gates on, and it can lag by a few seconds.
     *
     * @return $this
     */
    public function setRequests(int $requests): static
    {
        if (is_null($requests)) {
            throw new InvalidArgumentException('non-nullable requests cannot be null');
        }
        $this->container['requests'] = $requests;

        return $this;
    }

    /**
     * Gets quota
     *
     * @return int
     */
    public function getQuota(): int
    {
        return $this->container['quota'];
    }

    /**
     * Sets quota
     *
     * @param int $quota What the plan includes. Zero on a plan that includes none.
     *
     * @return $this
     */
    public function setQuota(int $quota): static
    {
        if (is_null($quota)) {
            throw new InvalidArgumentException('non-nullable quota cannot be null');
        }
        $this->container['quota'] = $quota;

        return $this;
    }

    /**
     * Gets hard_limit
     *
     * @return int|null
     */
    public function getHardLimit(): ?int
    {
        return $this->container['hard_limit'];
    }

    /**
     * Sets hard_limit
     *
     * @param int|null $hard_limit Where we stop serving. NULL means never, which is the normal state of an uncapped paid plan and is not the same as zero. Above the quota and below this, requests are served and billed as overage.
     *
     * @return $this
     */
    public function setHardLimit(?int $hard_limit): static
    {
        if (is_null($hard_limit)) {
            array_push($this->openAPINullablesSetToNull, 'hard_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hard_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hard_limit'] = $hard_limit;

        return $this;
    }

    /**
     * Gets window_start
     *
     * @return \DateTime
     */
    public function getWindowStart(): \DateTime
    {
        return $this->container['window_start'];
    }

    /**
     * Sets window_start
     *
     * @param \DateTime $window_start When the current allowance period began.
     *
     * @return $this
     */
    public function setWindowStart(\DateTime $window_start): static
    {
        if (is_null($window_start)) {
            throw new InvalidArgumentException('non-nullable window_start cannot be null');
        }
        $this->container['window_start'] = $window_start;

        return $this;
    }

    /**
     * Gets window_end
     *
     * @return \DateTime
     */
    public function getWindowEnd(): \DateTime
    {
        return $this->container['window_end'];
    }

    /**
     * Sets window_end
     *
     * @param \DateTime $window_end When the allowance next resets.
     *
     * @return $this
     */
    public function setWindowEnd(\DateTime $window_end): static
    {
        if (is_null($window_end)) {
            throw new InvalidArgumentException('non-nullable window_end cannot be null');
        }
        $this->container['window_end'] = $window_end;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


