<?php
/**
 * ApikeyDetail
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.21
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * ApikeyDetail Class Doc Comment
 *
 * @description Key METADATA. Never the key itself.
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ApikeyDetail implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ApikeyDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'key_prefix' => 'string',
        'created' => '\DateTime',
        'expires' => '\DateTime',
        'last_used_at' => '\DateTime',
        'revoked_at' => '\DateTime',
        'allowed_cidrs' => 'string[]',
        'allowed_scopes' => 'string[]',
        'retrievable' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => 'uuid',
        'name' => null,
        'key_prefix' => null,
        'created' => 'date-time',
        'expires' => 'date-time',
        'last_used_at' => 'date-time',
        'revoked_at' => 'date-time',
        'allowed_cidrs' => null,
        'allowed_scopes' => null,
        'retrievable' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'key_prefix' => false,
        'created' => false,
        'expires' => true,
        'last_used_at' => true,
        'revoked_at' => true,
        'allowed_cidrs' => false,
        'allowed_scopes' => false,
        'retrievable' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'key_prefix' => 'key_prefix',
        'created' => 'created',
        'expires' => 'expires',
        'last_used_at' => 'last_used_at',
        'revoked_at' => 'revoked_at',
        'allowed_cidrs' => 'allowed_cidrs',
        'allowed_scopes' => 'allowed_scopes',
        'retrievable' => 'retrievable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'key_prefix' => 'setKeyPrefix',
        'created' => 'setCreated',
        'expires' => 'setExpires',
        'last_used_at' => 'setLastUsedAt',
        'revoked_at' => 'setRevokedAt',
        'allowed_cidrs' => 'setAllowedCidrs',
        'allowed_scopes' => 'setAllowedScopes',
        'retrievable' => 'setRetrievable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'key_prefix' => 'getKeyPrefix',
        'created' => 'getCreated',
        'expires' => 'getExpires',
        'last_used_at' => 'getLastUsedAt',
        'revoked_at' => 'getRevokedAt',
        'allowed_cidrs' => 'getAllowedCidrs',
        'allowed_scopes' => 'getAllowedScopes',
        'retrievable' => 'getRetrievable'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('key_prefix', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('expires', $data ?? [], null);
        $this->setIfExists('last_used_at', $data ?? [], null);
        $this->setIfExists('revoked_at', $data ?? [], null);
        $this->setIfExists('allowed_cidrs', $data ?? [], null);
        $this->setIfExists('allowed_scopes', $data ?? [], null);
        $this->setIfExists('retrievable', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['key_prefix'] === null) {
            $invalidProperties[] = "'key_prefix' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets key_prefix
     *
     * @return string
     */
    public function getKeyPrefix(): string
    {
        return $this->container['key_prefix'];
    }

    /**
     * Sets key_prefix
     *
     * @param string $key_prefix The leading, non-secret part, so a key is recognisable without storing it.
     *
     * @return $this
     */
    public function setKeyPrefix(string $key_prefix): static
    {
        if (is_null($key_prefix)) {
            throw new InvalidArgumentException('non-nullable key_prefix cannot be null');
        }
        $this->container['key_prefix'] = $key_prefix;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated(): \DateTime
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created created
     *
     * @return $this
     */
    public function setCreated(\DateTime $created): static
    {
        if (is_null($created)) {
            throw new InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets expires
     *
     * @return \DateTime|null
     */
    public function getExpires(): ?\DateTime
    {
        return $this->container['expires'];
    }

    /**
     * Sets expires
     *
     * @param \DateTime|null $expires expires
     *
     * @return $this
     */
    public function setExpires(?\DateTime $expires): static
    {
        if (is_null($expires)) {
            array_push($this->openAPINullablesSetToNull, 'expires');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires'] = $expires;

        return $this;
    }

    /**
     * Gets last_used_at
     *
     * @return \DateTime|null
     */
    public function getLastUsedAt(): ?\DateTime
    {
        return $this->container['last_used_at'];
    }

    /**
     * Sets last_used_at
     *
     * @param \DateTime|null $last_used_at last_used_at
     *
     * @return $this
     */
    public function setLastUsedAt(?\DateTime $last_used_at): static
    {
        if (is_null($last_used_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_used_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_used_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_used_at'] = $last_used_at;

        return $this;
    }

    /**
     * Gets revoked_at
     *
     * @return \DateTime|null
     */
    public function getRevokedAt(): ?\DateTime
    {
        return $this->container['revoked_at'];
    }

    /**
     * Sets revoked_at
     *
     * @param \DateTime|null $revoked_at revoked_at
     *
     * @return $this
     */
    public function setRevokedAt(?\DateTime $revoked_at): static
    {
        if (is_null($revoked_at)) {
            array_push($this->openAPINullablesSetToNull, 'revoked_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('revoked_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['revoked_at'] = $revoked_at;

        return $this;
    }

    /**
     * Gets allowed_cidrs
     *
     * @return string[]|null
     */
    public function getAllowedCidrs(): ?array
    {
        return $this->container['allowed_cidrs'];
    }

    /**
     * Sets allowed_cidrs
     *
     * @param string[]|null $allowed_cidrs Source-IP allowlist. EMPTY MEANS UNRESTRICTED, not deny-all.
     *
     * @return $this
     */
    public function setAllowedCidrs(?array $allowed_cidrs): static
    {
        if (is_null($allowed_cidrs)) {
            throw new InvalidArgumentException('non-nullable allowed_cidrs cannot be null');
        }
        $this->container['allowed_cidrs'] = $allowed_cidrs;

        return $this;
    }

    /**
     * Gets allowed_scopes
     *
     * @return string[]|null
     */
    public function getAllowedScopes(): ?array
    {
        return $this->container['allowed_scopes'];
    }

    /**
     * Sets allowed_scopes
     *
     * @param string[]|null $allowed_scopes allowed_scopes
     *
     * @return $this
     */
    public function setAllowedScopes(?array $allowed_scopes): static
    {
        if (is_null($allowed_scopes)) {
            throw new InvalidArgumentException('non-nullable allowed_scopes cannot be null');
        }
        $this->container['allowed_scopes'] = $allowed_scopes;

        return $this;
    }

    /**
     * Gets retrievable
     *
     * @return bool|null
     */
    public function getRetrievable(): ?bool
    {
        return $this->container['retrievable'];
    }

    /**
     * Sets retrievable
     *
     * @param bool|null $retrievable Whether this key's secret can still be read back. False permanently for a key issued before secrets were stored recoverably.
     *
     * @return $this
     */
    public function setRetrievable(?bool $retrievable): static
    {
        if (is_null($retrievable)) {
            throw new InvalidArgumentException('non-nullable retrievable cannot be null');
        }
        $this->container['retrievable'] = $retrievable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


