<?php
/**
 * DatabaseFormat
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.13
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

/**
 * DatabaseFormat Class Doc Comment
 *
 * @description A file format a database version is published in.
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DatabaseFormat: string
{
    case CSVGZ = 'csvgz';

    case MMDB = 'mmdb';
}


