<?php
/**
 * DeviceAuthorization
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.15
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * DeviceAuthorization Class Doc Comment
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class DeviceAuthorization implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'DeviceAuthorization';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'device_code' => 'string',
        'user_code' => 'string',
        'verification_uri' => 'string',
        'verification_uri_complete' => 'string',
        'expires_in' => 'int',
        'interval' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'device_code' => null,
        'user_code' => null,
        'verification_uri' => null,
        'verification_uri_complete' => null,
        'expires_in' => null,
        'interval' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'device_code' => false,
        'user_code' => false,
        'verification_uri' => false,
        'verification_uri_complete' => false,
        'expires_in' => false,
        'interval' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'device_code' => 'device_code',
        'user_code' => 'user_code',
        'verification_uri' => 'verification_uri',
        'verification_uri_complete' => 'verification_uri_complete',
        'expires_in' => 'expires_in',
        'interval' => 'interval'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'device_code' => 'setDeviceCode',
        'user_code' => 'setUserCode',
        'verification_uri' => 'setVerificationUri',
        'verification_uri_complete' => 'setVerificationUriComplete',
        'expires_in' => 'setExpiresIn',
        'interval' => 'setInterval'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'device_code' => 'getDeviceCode',
        'user_code' => 'getUserCode',
        'verification_uri' => 'getVerificationUri',
        'verification_uri_complete' => 'getVerificationUriComplete',
        'expires_in' => 'getExpiresIn',
        'interval' => 'getInterval'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('device_code', $data ?? [], null);
        $this->setIfExists('user_code', $data ?? [], null);
        $this->setIfExists('verification_uri', $data ?? [], null);
        $this->setIfExists('verification_uri_complete', $data ?? [], null);
        $this->setIfExists('expires_in', $data ?? [], null);
        $this->setIfExists('interval', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['device_code'] === null) {
            $invalidProperties[] = "'device_code' can't be null";
        }
        if ($this->container['user_code'] === null) {
            $invalidProperties[] = "'user_code' can't be null";
        }
        if ($this->container['verification_uri'] === null) {
            $invalidProperties[] = "'verification_uri' can't be null";
        }
        if ($this->container['expires_in'] === null) {
            $invalidProperties[] = "'expires_in' can't be null";
        }
        if ($this->container['interval'] === null) {
            $invalidProperties[] = "'interval' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets device_code
     *
     * @return string
     */
    public function getDeviceCode(): string
    {
        return $this->container['device_code'];
    }

    /**
     * Sets device_code
     *
     * @param string $device_code Yours. Poll with it; never show it to anyone.
     *
     * @return $this
     */
    public function setDeviceCode(string $device_code): static
    {
        if (is_null($device_code)) {
            throw new InvalidArgumentException('non-nullable device_code cannot be null');
        }
        $this->container['device_code'] = $device_code;

        return $this;
    }

    /**
     * Gets user_code
     *
     * @return string
     */
    public function getUserCode(): string
    {
        return $this->container['user_code'];
    }

    /**
     * Sets user_code
     *
     * @param string $user_code Short and typable. This is what the person confirms.
     *
     * @return $this
     */
    public function setUserCode(string $user_code): static
    {
        if (is_null($user_code)) {
            throw new InvalidArgumentException('non-nullable user_code cannot be null');
        }
        $this->container['user_code'] = $user_code;

        return $this;
    }

    /**
     * Gets verification_uri
     *
     * @return string
     */
    public function getVerificationUri(): string
    {
        return $this->container['verification_uri'];
    }

    /**
     * Sets verification_uri
     *
     * @param string $verification_uri verification_uri
     *
     * @return $this
     */
    public function setVerificationUri(string $verification_uri): static
    {
        if (is_null($verification_uri)) {
            throw new InvalidArgumentException('non-nullable verification_uri cannot be null');
        }
        $this->container['verification_uri'] = $verification_uri;

        return $this;
    }

    /**
     * Gets verification_uri_complete
     *
     * @return string|null
     */
    public function getVerificationUriComplete(): ?string
    {
        return $this->container['verification_uri_complete'];
    }

    /**
     * Sets verification_uri_complete
     *
     * @param string|null $verification_uri_complete The same page with the code already filled in.
     *
     * @return $this
     */
    public function setVerificationUriComplete(?string $verification_uri_complete): static
    {
        if (is_null($verification_uri_complete)) {
            throw new InvalidArgumentException('non-nullable verification_uri_complete cannot be null');
        }
        $this->container['verification_uri_complete'] = $verification_uri_complete;

        return $this;
    }

    /**
     * Gets expires_in
     *
     * @return int
     */
    public function getExpiresIn(): int
    {
        return $this->container['expires_in'];
    }

    /**
     * Sets expires_in
     *
     * @param int $expires_in expires_in
     *
     * @return $this
     */
    public function setExpiresIn(int $expires_in): static
    {
        if (is_null($expires_in)) {
            throw new InvalidArgumentException('non-nullable expires_in cannot be null');
        }
        $this->container['expires_in'] = $expires_in;

        return $this;
    }

    /**
     * Gets interval
     *
     * @return int
     */
    public function getInterval(): int
    {
        return $this->container['interval'];
    }

    /**
     * Sets interval
     *
     * @param int $interval Seconds between polls.
     *
     * @return $this
     */
    public function setInterval(int $interval): static
    {
        if (is_null($interval)) {
            throw new InvalidArgumentException('non-nullable interval cannot be null');
        }
        $this->container['interval'] = $interval;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


