<?php
/**
 * LicensedDataset
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * LicensedDataset Class Doc Comment
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LicensedDataset implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'LicensedDataset';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'summary' => 'string',
        'retired' => 'bool',
        'redistribution' => 'string',
        'starts' => '\DateTime',
        'expires' => '\DateTime',
        'in_term' => 'bool',
        'formats' => '\VPNDetection\Internal\Model\DatasetFormatSize[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => null,
        'name' => null,
        'summary' => null,
        'retired' => null,
        'redistribution' => null,
        'starts' => 'date-time',
        'expires' => 'date-time',
        'in_term' => null,
        'formats' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'summary' => false,
        'retired' => false,
        'redistribution' => false,
        'starts' => false,
        'expires' => true,
        'in_term' => false,
        'formats' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'summary' => 'summary',
        'retired' => 'retired',
        'redistribution' => 'redistribution',
        'starts' => 'starts',
        'expires' => 'expires',
        'in_term' => 'in_term',
        'formats' => 'formats'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'summary' => 'setSummary',
        'retired' => 'setRetired',
        'redistribution' => 'setRedistribution',
        'starts' => 'setStarts',
        'expires' => 'setExpires',
        'in_term' => 'setInTerm',
        'formats' => 'setFormats'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'summary' => 'getSummary',
        'retired' => 'getRetired',
        'redistribution' => 'getRedistribution',
        'starts' => 'getStarts',
        'expires' => 'getExpires',
        'in_term' => 'getInTerm',
        'formats' => 'getFormats'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const REDISTRIBUTION_EVALUATION = 'evaluation';
    public const REDISTRIBUTION_INTERNAL = 'internal';
    public const REDISTRIBUTION_REDISTRIBUTE = 'redistribute';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getRedistributionAllowableValues()
    {
        return [
            self::REDISTRIBUTION_EVALUATION,
            self::REDISTRIBUTION_INTERNAL,
            self::REDISTRIBUTION_REDISTRIBUTE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('retired', $data ?? [], null);
        $this->setIfExists('redistribution', $data ?? [], null);
        $this->setIfExists('starts', $data ?? [], null);
        $this->setIfExists('expires', $data ?? [], null);
        $this->setIfExists('in_term', $data ?? [], null);
        $this->setIfExists('formats', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['redistribution'] === null) {
            $invalidProperties[] = "'redistribution' can't be null";
        }
        $allowedValues = self::getRedistributionAllowableValues();
        if (!is_null($this->container['redistribution']) && !in_array($this->container['redistribution'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'redistribution', must be one of '%s'",
                $this->container['redistribution'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['in_term'] === null) {
            $invalidProperties[] = "'in_term' can't be null";
        }
        if ($this->container['formats'] === null) {
            $invalidProperties[] = "'formats' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string|null
     */
    public function getSummary(): ?string
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string|null $summary summary
     *
     * @return $this
     */
    public function setSummary(?string $summary): static
    {
        if (is_null($summary)) {
            throw new InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets retired
     *
     * @return bool|null
     */
    public function getRetired(): ?bool
    {
        return $this->container['retired'];
    }

    /**
     * Sets retired
     *
     * @param bool|null $retired Licensed but no longer published. Talk to us.
     *
     * @return $this
     */
    public function setRetired(?bool $retired): static
    {
        if (is_null($retired)) {
            throw new InvalidArgumentException('non-nullable retired cannot be null');
        }
        $this->container['retired'] = $retired;

        return $this;
    }

    /**
     * Gets redistribution
     *
     * @return string
     */
    public function getRedistribution(): string
    {
        return $this->container['redistribution'];
    }

    /**
     * Sets redistribution
     *
     * @param string $redistribution What your license permits you to do with the data
     *
     * @return $this
     */
    public function setRedistribution(string $redistribution): static
    {
        if (is_null($redistribution)) {
            throw new InvalidArgumentException('non-nullable redistribution cannot be null');
        }
        $allowedValues = self::getRedistributionAllowableValues();
        if (!in_array($redistribution, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'redistribution', must be one of '%s'",
                    $redistribution,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['redistribution'] = $redistribution;

        return $this;
    }

    /**
     * Gets starts
     *
     * @return \DateTime|null
     */
    public function getStarts(): ?\DateTime
    {
        return $this->container['starts'];
    }

    /**
     * Sets starts
     *
     * @param \DateTime|null $starts starts
     *
     * @return $this
     */
    public function setStarts(?\DateTime $starts): static
    {
        if (is_null($starts)) {
            throw new InvalidArgumentException('non-nullable starts cannot be null');
        }
        $this->container['starts'] = $starts;

        return $this;
    }

    /**
     * Gets expires
     *
     * @return \DateTime|null
     */
    public function getExpires(): ?\DateTime
    {
        return $this->container['expires'];
    }

    /**
     * Sets expires
     *
     * @param \DateTime|null $expires expires
     *
     * @return $this
     */
    public function setExpires(?\DateTime $expires): static
    {
        if (is_null($expires)) {
            array_push($this->openAPINullablesSetToNull, 'expires');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires'] = $expires;

        return $this;
    }

    /**
     * Gets in_term
     *
     * @return bool
     */
    public function getInTerm(): bool
    {
        return $this->container['in_term'];
    }

    /**
     * Sets in_term
     *
     * @param bool $in_term False when the license has lapsed; downloads are refused
     *
     * @return $this
     */
    public function setInTerm(bool $in_term): static
    {
        if (is_null($in_term)) {
            throw new InvalidArgumentException('non-nullable in_term cannot be null');
        }
        $this->container['in_term'] = $in_term;

        return $this;
    }

    /**
     * Gets formats
     *
     * @return \VPNDetection\Internal\Model\DatasetFormatSize[]
     */
    public function getFormats(): array
    {
        return $this->container['formats'];
    }

    /**
     * Sets formats
     *
     * @param \VPNDetection\Internal\Model\DatasetFormatSize[] $formats formats
     *
     * @return $this
     */
    public function setFormats(array $formats): static
    {
        if (is_null($formats)) {
            throw new InvalidArgumentException('non-nullable formats cannot be null');
        }
        $this->container['formats'] = $formats;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


