<?php
/**
 * LookupResponse
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * LookupResponse Class Doc Comment
 *
 * @description The union of every plan&#39;s answer. Only &#x60;ip&#x60; and &#x60;is_vpn&#x60; are guaranteed; each remaining field is present when your plan includes it, and absent otherwise. A client that must work across plans should treat an absent flag as unknown rather than as &#x60;false&#x60;.
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LookupResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'LookupResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'ip' => 'string',
        'is_vpn' => 'bool',
        'is_hosting' => 'bool',
        'is_relay' => 'bool',
        'is_tor' => 'bool',
        'is_cdn' => 'bool',
        'is_resproxy' => 'bool',
        'is_dcproxy' => 'bool',
        'is_mobproxy' => 'bool',
        'vpn' => '\VPNDetection\Internal\Model\VpnDetail',
        'hosting' => '\VPNDetection\Internal\Model\ClassDetail',
        'relay' => '\VPNDetection\Internal\Model\ClassDetail',
        'tor' => '\VPNDetection\Internal\Model\ClassDetail',
        'cdn' => '\VPNDetection\Internal\Model\ClassDetail',
        'resproxy' => '\VPNDetection\Internal\Model\ProxyDetail',
        'dcproxy' => '\VPNDetection\Internal\Model\ProxyDetail',
        'mobproxy' => '\VPNDetection\Internal\Model\ProxyDetail'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'ip' => null,
        'is_vpn' => null,
        'is_hosting' => null,
        'is_relay' => null,
        'is_tor' => null,
        'is_cdn' => null,
        'is_resproxy' => null,
        'is_dcproxy' => null,
        'is_mobproxy' => null,
        'vpn' => null,
        'hosting' => null,
        'relay' => null,
        'tor' => null,
        'cdn' => null,
        'resproxy' => null,
        'dcproxy' => null,
        'mobproxy' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'ip' => false,
        'is_vpn' => false,
        'is_hosting' => false,
        'is_relay' => false,
        'is_tor' => false,
        'is_cdn' => false,
        'is_resproxy' => false,
        'is_dcproxy' => false,
        'is_mobproxy' => false,
        'vpn' => false,
        'hosting' => false,
        'relay' => false,
        'tor' => false,
        'cdn' => false,
        'resproxy' => false,
        'dcproxy' => false,
        'mobproxy' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'ip' => 'ip',
        'is_vpn' => 'is_vpn',
        'is_hosting' => 'is_hosting',
        'is_relay' => 'is_relay',
        'is_tor' => 'is_tor',
        'is_cdn' => 'is_cdn',
        'is_resproxy' => 'is_resproxy',
        'is_dcproxy' => 'is_dcproxy',
        'is_mobproxy' => 'is_mobproxy',
        'vpn' => 'vpn',
        'hosting' => 'hosting',
        'relay' => 'relay',
        'tor' => 'tor',
        'cdn' => 'cdn',
        'resproxy' => 'resproxy',
        'dcproxy' => 'dcproxy',
        'mobproxy' => 'mobproxy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'ip' => 'setIp',
        'is_vpn' => 'setIsVpn',
        'is_hosting' => 'setIsHosting',
        'is_relay' => 'setIsRelay',
        'is_tor' => 'setIsTor',
        'is_cdn' => 'setIsCdn',
        'is_resproxy' => 'setIsResproxy',
        'is_dcproxy' => 'setIsDcproxy',
        'is_mobproxy' => 'setIsMobproxy',
        'vpn' => 'setVpn',
        'hosting' => 'setHosting',
        'relay' => 'setRelay',
        'tor' => 'setTor',
        'cdn' => 'setCdn',
        'resproxy' => 'setResproxy',
        'dcproxy' => 'setDcproxy',
        'mobproxy' => 'setMobproxy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'ip' => 'getIp',
        'is_vpn' => 'getIsVpn',
        'is_hosting' => 'getIsHosting',
        'is_relay' => 'getIsRelay',
        'is_tor' => 'getIsTor',
        'is_cdn' => 'getIsCdn',
        'is_resproxy' => 'getIsResproxy',
        'is_dcproxy' => 'getIsDcproxy',
        'is_mobproxy' => 'getIsMobproxy',
        'vpn' => 'getVpn',
        'hosting' => 'getHosting',
        'relay' => 'getRelay',
        'tor' => 'getTor',
        'cdn' => 'getCdn',
        'resproxy' => 'getResproxy',
        'dcproxy' => 'getDcproxy',
        'mobproxy' => 'getMobproxy'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ip', $data ?? [], null);
        $this->setIfExists('is_vpn', $data ?? [], null);
        $this->setIfExists('is_hosting', $data ?? [], null);
        $this->setIfExists('is_relay', $data ?? [], null);
        $this->setIfExists('is_tor', $data ?? [], null);
        $this->setIfExists('is_cdn', $data ?? [], null);
        $this->setIfExists('is_resproxy', $data ?? [], null);
        $this->setIfExists('is_dcproxy', $data ?? [], null);
        $this->setIfExists('is_mobproxy', $data ?? [], null);
        $this->setIfExists('vpn', $data ?? [], null);
        $this->setIfExists('hosting', $data ?? [], null);
        $this->setIfExists('relay', $data ?? [], null);
        $this->setIfExists('tor', $data ?? [], null);
        $this->setIfExists('cdn', $data ?? [], null);
        $this->setIfExists('resproxy', $data ?? [], null);
        $this->setIfExists('dcproxy', $data ?? [], null);
        $this->setIfExists('mobproxy', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['ip'] === null) {
            $invalidProperties[] = "'ip' can't be null";
        }
        if ($this->container['is_vpn'] === null) {
            $invalidProperties[] = "'is_vpn' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ip
     *
     * @return string
     */
    public function getIp(): string
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string $ip The address that was looked up, normalized.
     *
     * @return $this
     */
    public function setIp(string $ip): static
    {
        if (is_null($ip)) {
            throw new InvalidArgumentException('non-nullable ip cannot be null');
        }
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets is_vpn
     *
     * @return bool
     */
    public function getIsVpn(): bool
    {
        return $this->container['is_vpn'];
    }

    /**
     * Sets is_vpn
     *
     * @param bool $is_vpn Whether the address is VPN infrastructure. Keys off presence in the VPN dataset, so an unattributed range with no provider is still `true`.
     *
     * @return $this
     */
    public function setIsVpn(bool $is_vpn): static
    {
        if (is_null($is_vpn)) {
            throw new InvalidArgumentException('non-nullable is_vpn cannot be null');
        }
        $this->container['is_vpn'] = $is_vpn;

        return $this;
    }

    /**
     * Gets is_hosting
     *
     * @return bool|null
     */
    public function getIsHosting(): ?bool
    {
        return $this->container['is_hosting'];
    }

    /**
     * Sets is_hosting
     *
     * @param bool|null $is_hosting Whether the address belongs to a hosting or cloud provider. Starter and above.
     *
     * @return $this
     */
    public function setIsHosting(?bool $is_hosting): static
    {
        if (is_null($is_hosting)) {
            throw new InvalidArgumentException('non-nullable is_hosting cannot be null');
        }
        $this->container['is_hosting'] = $is_hosting;

        return $this;
    }

    /**
     * Gets is_relay
     *
     * @return bool|null
     */
    public function getIsRelay(): ?bool
    {
        return $this->container['is_relay'];
    }

    /**
     * Sets is_relay
     *
     * @param bool|null $is_relay Whether the address is a privacy relay egress. Starter and above.
     *
     * @return $this
     */
    public function setIsRelay(?bool $is_relay): static
    {
        if (is_null($is_relay)) {
            throw new InvalidArgumentException('non-nullable is_relay cannot be null');
        }
        $this->container['is_relay'] = $is_relay;

        return $this;
    }

    /**
     * Gets is_tor
     *
     * @return bool|null
     */
    public function getIsTor(): ?bool
    {
        return $this->container['is_tor'];
    }

    /**
     * Sets is_tor
     *
     * @param bool|null $is_tor Whether the address is a Tor node. Starter and above.
     *
     * @return $this
     */
    public function setIsTor(?bool $is_tor): static
    {
        if (is_null($is_tor)) {
            throw new InvalidArgumentException('non-nullable is_tor cannot be null');
        }
        $this->container['is_tor'] = $is_tor;

        return $this;
    }

    /**
     * Gets is_cdn
     *
     * @return bool|null
     */
    public function getIsCdn(): ?bool
    {
        return $this->container['is_cdn'];
    }

    /**
     * Sets is_cdn
     *
     * @param bool|null $is_cdn Whether the address belongs to a CDN. Starter and above.
     *
     * @return $this
     */
    public function setIsCdn(?bool $is_cdn): static
    {
        if (is_null($is_cdn)) {
            throw new InvalidArgumentException('non-nullable is_cdn cannot be null');
        }
        $this->container['is_cdn'] = $is_cdn;

        return $this;
    }

    /**
     * Gets is_resproxy
     *
     * @return bool|null
     */
    public function getIsResproxy(): ?bool
    {
        return $this->container['is_resproxy'];
    }

    /**
     * Sets is_resproxy
     *
     * @param bool|null $is_resproxy Whether the address was seen in a residential proxy pool. Max only.
     *
     * @return $this
     */
    public function setIsResproxy(?bool $is_resproxy): static
    {
        if (is_null($is_resproxy)) {
            throw new InvalidArgumentException('non-nullable is_resproxy cannot be null');
        }
        $this->container['is_resproxy'] = $is_resproxy;

        return $this;
    }

    /**
     * Gets is_dcproxy
     *
     * @return bool|null
     */
    public function getIsDcproxy(): ?bool
    {
        return $this->container['is_dcproxy'];
    }

    /**
     * Sets is_dcproxy
     *
     * @param bool|null $is_dcproxy Whether the address was seen in a datacenter proxy pool. Max only.
     *
     * @return $this
     */
    public function setIsDcproxy(?bool $is_dcproxy): static
    {
        if (is_null($is_dcproxy)) {
            throw new InvalidArgumentException('non-nullable is_dcproxy cannot be null');
        }
        $this->container['is_dcproxy'] = $is_dcproxy;

        return $this;
    }

    /**
     * Gets is_mobproxy
     *
     * @return bool|null
     */
    public function getIsMobproxy(): ?bool
    {
        return $this->container['is_mobproxy'];
    }

    /**
     * Sets is_mobproxy
     *
     * @param bool|null $is_mobproxy Whether the address was seen in a mobile proxy pool. Max only.
     *
     * @return $this
     */
    public function setIsMobproxy(?bool $is_mobproxy): static
    {
        if (is_null($is_mobproxy)) {
            throw new InvalidArgumentException('non-nullable is_mobproxy cannot be null');
        }
        $this->container['is_mobproxy'] = $is_mobproxy;

        return $this;
    }

    /**
     * Gets vpn
     *
     * @return \VPNDetection\Internal\Model\VpnDetail|null
     */
    public function getVpn(): ?\VPNDetection\Internal\Model\VpnDetail
    {
        return $this->container['vpn'];
    }

    /**
     * Sets vpn
     *
     * @param \VPNDetection\Internal\Model\VpnDetail|null $vpn Detail for `is_vpn`. Empty when `is_vpn` is false. Starter and above.
     *
     * @return $this
     */
    public function setVpn(?\VPNDetection\Internal\Model\VpnDetail $vpn): static
    {
        if (is_null($vpn)) {
            throw new InvalidArgumentException('non-nullable vpn cannot be null');
        }
        $this->container['vpn'] = $vpn;

        return $this;
    }

    /**
     * Gets hosting
     *
     * @return \VPNDetection\Internal\Model\ClassDetail|null
     */
    public function getHosting(): ?\VPNDetection\Internal\Model\ClassDetail
    {
        return $this->container['hosting'];
    }

    /**
     * Sets hosting
     *
     * @param \VPNDetection\Internal\Model\ClassDetail|null $hosting Detail for `is_hosting`. Empty when false. Scale and above.
     *
     * @return $this
     */
    public function setHosting(?\VPNDetection\Internal\Model\ClassDetail $hosting): static
    {
        if (is_null($hosting)) {
            throw new InvalidArgumentException('non-nullable hosting cannot be null');
        }
        $this->container['hosting'] = $hosting;

        return $this;
    }

    /**
     * Gets relay
     *
     * @return \VPNDetection\Internal\Model\ClassDetail|null
     */
    public function getRelay(): ?\VPNDetection\Internal\Model\ClassDetail
    {
        return $this->container['relay'];
    }

    /**
     * Sets relay
     *
     * @param \VPNDetection\Internal\Model\ClassDetail|null $relay Detail for `is_relay`. Empty when false. Scale and above.
     *
     * @return $this
     */
    public function setRelay(?\VPNDetection\Internal\Model\ClassDetail $relay): static
    {
        if (is_null($relay)) {
            throw new InvalidArgumentException('non-nullable relay cannot be null');
        }
        $this->container['relay'] = $relay;

        return $this;
    }

    /**
     * Gets tor
     *
     * @return \VPNDetection\Internal\Model\ClassDetail|null
     */
    public function getTor(): ?\VPNDetection\Internal\Model\ClassDetail
    {
        return $this->container['tor'];
    }

    /**
     * Sets tor
     *
     * @param \VPNDetection\Internal\Model\ClassDetail|null $tor Detail for `is_tor`. Empty when false. Scale and above. The tor dataset carries no provider, so `provider` is always an empty string.
     *
     * @return $this
     */
    public function setTor(?\VPNDetection\Internal\Model\ClassDetail $tor): static
    {
        if (is_null($tor)) {
            throw new InvalidArgumentException('non-nullable tor cannot be null');
        }
        $this->container['tor'] = $tor;

        return $this;
    }

    /**
     * Gets cdn
     *
     * @return \VPNDetection\Internal\Model\ClassDetail|null
     */
    public function getCdn(): ?\VPNDetection\Internal\Model\ClassDetail
    {
        return $this->container['cdn'];
    }

    /**
     * Sets cdn
     *
     * @param \VPNDetection\Internal\Model\ClassDetail|null $cdn Detail for `is_cdn`. Empty when false. Scale and above.
     *
     * @return $this
     */
    public function setCdn(?\VPNDetection\Internal\Model\ClassDetail $cdn): static
    {
        if (is_null($cdn)) {
            throw new InvalidArgumentException('non-nullable cdn cannot be null');
        }
        $this->container['cdn'] = $cdn;

        return $this;
    }

    /**
     * Gets resproxy
     *
     * @return \VPNDetection\Internal\Model\ProxyDetail|null
     */
    public function getResproxy(): ?\VPNDetection\Internal\Model\ProxyDetail
    {
        return $this->container['resproxy'];
    }

    /**
     * Sets resproxy
     *
     * @param \VPNDetection\Internal\Model\ProxyDetail|null $resproxy Detail for `is_resproxy`. Empty when false. Max only.
     *
     * @return $this
     */
    public function setResproxy(?\VPNDetection\Internal\Model\ProxyDetail $resproxy): static
    {
        if (is_null($resproxy)) {
            throw new InvalidArgumentException('non-nullable resproxy cannot be null');
        }
        $this->container['resproxy'] = $resproxy;

        return $this;
    }

    /**
     * Gets dcproxy
     *
     * @return \VPNDetection\Internal\Model\ProxyDetail|null
     */
    public function getDcproxy(): ?\VPNDetection\Internal\Model\ProxyDetail
    {
        return $this->container['dcproxy'];
    }

    /**
     * Sets dcproxy
     *
     * @param \VPNDetection\Internal\Model\ProxyDetail|null $dcproxy Detail for `is_dcproxy`. Empty when false. Max only.
     *
     * @return $this
     */
    public function setDcproxy(?\VPNDetection\Internal\Model\ProxyDetail $dcproxy): static
    {
        if (is_null($dcproxy)) {
            throw new InvalidArgumentException('non-nullable dcproxy cannot be null');
        }
        $this->container['dcproxy'] = $dcproxy;

        return $this;
    }

    /**
     * Gets mobproxy
     *
     * @return \VPNDetection\Internal\Model\ProxyDetail|null
     */
    public function getMobproxy(): ?\VPNDetection\Internal\Model\ProxyDetail
    {
        return $this->container['mobproxy'];
    }

    /**
     * Sets mobproxy
     *
     * @param \VPNDetection\Internal\Model\ProxyDetail|null $mobproxy Detail for `is_mobproxy`. Empty when false. Max only.
     *
     * @return $this
     */
    public function setMobproxy(?\VPNDetection\Internal\Model\ProxyDetail $mobproxy): static
    {
        if (is_null($mobproxy)) {
            throw new InvalidArgumentException('non-nullable mobproxy cannot be null');
        }
        $this->container['mobproxy'] = $mobproxy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


