<?php
/**
 * ProxyDetail
 *
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the datasets behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.03
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use VPNDetection\Internal\ObjectSerializer;

/**
 * ProxyDetail Class Doc Comment
 *
 * @description The shared detail shape for the residential, datacenter and mobile proxy families, measured over a rolling 90 day window. Every key is present when the object is populated; the object is &#x60;{}&#x60; when its flag is false.
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProxyDetail implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ProxyDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'provider' => 'string',
        'first_seen' => '\DateTime',
        'last_seen' => '\DateTime',
        'hits' => 'int',
        'hits_days_pct' => 'int',
        'providers_num' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'provider' => null,
        'first_seen' => 'date',
        'last_seen' => 'date',
        'hits' => null,
        'hits_days_pct' => null,
        'providers_num' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'provider' => false,
        'first_seen' => false,
        'last_seen' => false,
        'hits' => false,
        'hits_days_pct' => false,
        'providers_num' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'provider' => 'provider',
        'first_seen' => 'first_seen',
        'last_seen' => 'last_seen',
        'hits' => 'hits',
        'hits_days_pct' => 'hits_days_pct',
        'providers_num' => 'providers_num'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'provider' => 'setProvider',
        'first_seen' => 'setFirstSeen',
        'last_seen' => 'setLastSeen',
        'hits' => 'setHits',
        'hits_days_pct' => 'setHitsDaysPct',
        'providers_num' => 'setProvidersNum'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'provider' => 'getProvider',
        'first_seen' => 'getFirstSeen',
        'last_seen' => 'getLastSeen',
        'hits' => 'getHits',
        'hits_days_pct' => 'getHitsDaysPct',
        'providers_num' => 'getProvidersNum'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('first_seen', $data ?? [], null);
        $this->setIfExists('last_seen', $data ?? [], null);
        $this->setIfExists('hits', $data ?? [], null);
        $this->setIfExists('hits_days_pct', $data ?? [], null);
        $this->setIfExists('providers_num', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets provider
     *
     * @return string|null
     */
    public function getProvider(): ?string
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string|null $provider The proxy network, or an empty string where unattributed.
     *
     * @return $this
     */
    public function setProvider(?string $provider): static
    {
        if (is_null($provider)) {
            throw new InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets first_seen
     *
     * @return \DateTime|null
     */
    public function getFirstSeen(): ?\DateTime
    {
        return $this->container['first_seen'];
    }

    /**
     * Sets first_seen
     *
     * @param \DateTime|null $first_seen The earliest date within the window this address was seen in the pool.
     *
     * @return $this
     */
    public function setFirstSeen(?\DateTime $first_seen): static
    {
        if (is_null($first_seen)) {
            throw new InvalidArgumentException('non-nullable first_seen cannot be null');
        }
        $this->container['first_seen'] = $first_seen;

        return $this;
    }

    /**
     * Gets last_seen
     *
     * @return \DateTime|null
     */
    public function getLastSeen(): ?\DateTime
    {
        return $this->container['last_seen'];
    }

    /**
     * Sets last_seen
     *
     * @param \DateTime|null $last_seen The most recent date within the window this address was seen in the pool.
     *
     * @return $this
     */
    public function setLastSeen(?\DateTime $last_seen): static
    {
        if (is_null($last_seen)) {
            throw new InvalidArgumentException('non-nullable last_seen cannot be null');
        }
        $this->container['last_seen'] = $last_seen;

        return $this;
    }

    /**
     * Gets hits
     *
     * @return int|null
     */
    public function getHits(): ?int
    {
        return $this->container['hits'];
    }

    /**
     * Sets hits
     *
     * @param int|null $hits How many times the address was observed in the pool during the window.
     *
     * @return $this
     */
    public function setHits(?int $hits): static
    {
        if (is_null($hits)) {
            throw new InvalidArgumentException('non-nullable hits cannot be null');
        }
        $this->container['hits'] = $hits;

        return $this;
    }

    /**
     * Gets hits_days_pct
     *
     * @return int|null
     */
    public function getHitsDaysPct(): ?int
    {
        return $this->container['hits_days_pct'];
    }

    /**
     * Sets hits_days_pct
     *
     * @param int|null $hits_days_pct The share of days in the window on which the address was seen, as a percentage. A high value means a stable pool member rather than a one-off sighting.
     *
     * @return $this
     */
    public function setHitsDaysPct(?int $hits_days_pct): static
    {
        if (is_null($hits_days_pct)) {
            throw new InvalidArgumentException('non-nullable hits_days_pct cannot be null');
        }
        $this->container['hits_days_pct'] = $hits_days_pct;

        return $this;
    }

    /**
     * Gets providers_num
     *
     * @return int|null
     */
    public function getProvidersNum(): ?int
    {
        return $this->container['providers_num'];
    }

    /**
     * Sets providers_num
     *
     * @param int|null $providers_num How many distinct proxy networks this address was seen in.
     *
     * @return $this
     */
    public function setProvidersNum(?int $providers_num): static
    {
        if (is_null($providers_num)) {
            throw new InvalidArgumentException('non-nullable providers_num cannot be null');
        }
        $this->container['providers_num'] = $providers_num;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


