<?php
/**
 * APIKeysApi
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.15
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use VPNDetection\Internal\ApiException;
use VPNDetection\Internal\Configuration;
use VPNDetection\Internal\HeaderSelector;
use VPNDetection\Internal\ObjectSerializer;

/**
 * APIKeysApi Class Doc Comment
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIKeysApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'accountCreateApikey' => [
            'application/json',
        ],
        'accountListApikeys' => [
            'application/json',
        ],
        'accountRevealApikey' => [
            'application/json',
        ],
        'accountRevokeApikey' => [
            'application/json',
        ],
        'accountRotateApikey' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation accountCreateApikey
     *
     * Create an API key
     *
     * @param  \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request account_create_apikey_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountCreateApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc
     */
    public function accountCreateApikey(
        \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request,
        string $contentType = self::contentTypes['accountCreateApikey'][0]
    ): \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc
    {
        list($response) = $this->accountCreateApikeyWithHttpInfo($account_create_apikey_request, $contentType);
        return $response;
    }

    /**
     * Operation accountCreateApikeyWithHttpInfo
     *
     * Create an API key
     *
     * @param  \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountCreateApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function accountCreateApikeyWithHttpInfo(
        \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request,
        string $contentType = self::contentTypes['accountCreateApikey'][0]
    ): array
    {
        $request = $this->accountCreateApikeyRequest($account_create_apikey_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountCreatedApikey',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\AccountCreatedApikey',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountCreatedApikey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation accountCreateApikeyAsync
     *
     * Create an API key
     *
     * @param  \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountCreateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountCreateApikeyAsync(
        \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request,
        string $contentType = self::contentTypes['accountCreateApikey'][0]
    ): PromiseInterface
    {
        return $this->accountCreateApikeyAsyncWithHttpInfo($account_create_apikey_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation accountCreateApikeyAsyncWithHttpInfo
     *
     * Create an API key
     *
     * @param  \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountCreateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountCreateApikeyAsyncWithHttpInfo(
        \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request,
        string $contentType = self::contentTypes['accountCreateApikey'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\AccountCreatedApikey';
        $request = $this->accountCreateApikeyRequest($account_create_apikey_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'accountCreateApikey'
     *
     * @param  \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountCreateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function accountCreateApikeyRequest(
        \VPNDetection\Internal\Model\AccountCreateApikeyRequest $account_create_apikey_request,
        string $contentType = self::contentTypes['accountCreateApikey'][0]
    ): Request
    {
        // verify the required parameter 'account_create_apikey_request' is set
        if ($account_create_apikey_request === null || (is_array($account_create_apikey_request) && count($account_create_apikey_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $account_create_apikey_request when calling accountCreateApikey'
            );
        }

        $resourcePath = '/api/v1/account/apikeys';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($account_create_apikey_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($account_create_apikey_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $account_create_apikey_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation accountListApikeys
     *
     * List your API keys
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountListApikeys'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\ApikeyList|\VPNDetection\Internal\Model\AccountRc
     */
    public function accountListApikeys(
        string $contentType = self::contentTypes['accountListApikeys'][0]
    ): \VPNDetection\Internal\Model\ApikeyList|\VPNDetection\Internal\Model\AccountRc
    {
        list($response) = $this->accountListApikeysWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation accountListApikeysWithHttpInfo
     *
     * List your API keys
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountListApikeys'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\ApikeyList|\VPNDetection\Internal\Model\AccountRc, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function accountListApikeysWithHttpInfo(
        string $contentType = self::contentTypes['accountListApikeys'][0]
    ): array
    {
        $request = $this->accountListApikeysRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\ApikeyList',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\ApikeyList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\ApikeyList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation accountListApikeysAsync
     *
     * List your API keys
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountListApikeys'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountListApikeysAsync(
        string $contentType = self::contentTypes['accountListApikeys'][0]
    ): PromiseInterface
    {
        return $this->accountListApikeysAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation accountListApikeysAsyncWithHttpInfo
     *
     * List your API keys
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountListApikeys'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountListApikeysAsyncWithHttpInfo(
        string $contentType = self::contentTypes['accountListApikeys'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\ApikeyList';
        $request = $this->accountListApikeysRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'accountListApikeys'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountListApikeys'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function accountListApikeysRequest(
        string $contentType = self::contentTypes['accountListApikeys'][0]
    ): Request
    {

        $resourcePath = '/api/v1/account/apikeys';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation accountRevealApikey
     *
     * Read back a key&#39;s secret
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevealApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\AccountRevealedApikey|\VPNDetection\Internal\Model\AccountRc
     */
    public function accountRevealApikey(
        string $id,
        string $contentType = self::contentTypes['accountRevealApikey'][0]
    ): \VPNDetection\Internal\Model\AccountRevealedApikey|\VPNDetection\Internal\Model\AccountRc
    {
        list($response) = $this->accountRevealApikeyWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation accountRevealApikeyWithHttpInfo
     *
     * Read back a key&#39;s secret
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevealApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\AccountRevealedApikey|\VPNDetection\Internal\Model\AccountRc, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function accountRevealApikeyWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRevealApikey'][0]
    ): array
    {
        $request = $this->accountRevealApikeyRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRevealedApikey',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\AccountRevealedApikey',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRevealedApikey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation accountRevealApikeyAsync
     *
     * Read back a key&#39;s secret
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevealApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRevealApikeyAsync(
        string $id,
        string $contentType = self::contentTypes['accountRevealApikey'][0]
    ): PromiseInterface
    {
        return $this->accountRevealApikeyAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation accountRevealApikeyAsyncWithHttpInfo
     *
     * Read back a key&#39;s secret
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevealApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRevealApikeyAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRevealApikey'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\AccountRevealedApikey';
        $request = $this->accountRevealApikeyRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'accountRevealApikey'
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevealApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function accountRevealApikeyRequest(
        string $id,
        string $contentType = self::contentTypes['accountRevealApikey'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling accountRevealApikey'
            );
        }

        $resourcePath = '/api/v1/account/apikeys/{id}/reveal';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation accountRevokeApikey
     *
     * Revoke an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevokeApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\AccountRc
     */
    public function accountRevokeApikey(
        string $id,
        string $contentType = self::contentTypes['accountRevokeApikey'][0]
    ): \VPNDetection\Internal\Model\AccountRc
    {
        list($response) = $this->accountRevokeApikeyWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation accountRevokeApikeyWithHttpInfo
     *
     * Revoke an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevokeApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\AccountRc, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function accountRevokeApikeyWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRevokeApikey'][0]
    ): array
    {
        $request = $this->accountRevokeApikeyRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\AccountRc',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation accountRevokeApikeyAsync
     *
     * Revoke an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevokeApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRevokeApikeyAsync(
        string $id,
        string $contentType = self::contentTypes['accountRevokeApikey'][0]
    ): PromiseInterface
    {
        return $this->accountRevokeApikeyAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation accountRevokeApikeyAsyncWithHttpInfo
     *
     * Revoke an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevokeApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRevokeApikeyAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRevokeApikey'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\AccountRc';
        $request = $this->accountRevokeApikeyRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'accountRevokeApikey'
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRevokeApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function accountRevokeApikeyRequest(
        string $id,
        string $contentType = self::contentTypes['accountRevokeApikey'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling accountRevokeApikey'
            );
        }

        $resourcePath = '/api/v1/account/apikeys/{id}/revoke';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation accountRotateApikey
     *
     * Rotate an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRotateApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc
     */
    public function accountRotateApikey(
        string $id,
        string $contentType = self::contentTypes['accountRotateApikey'][0]
    ): \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc
    {
        list($response) = $this->accountRotateApikeyWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation accountRotateApikeyWithHttpInfo
     *
     * Rotate an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRotateApikey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\AccountCreatedApikey|\VPNDetection\Internal\Model\AccountRc, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function accountRotateApikeyWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRotateApikey'][0]
    ): array
    {
        $request = $this->accountRotateApikeyRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountCreatedApikey',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\AccountRc',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\AccountCreatedApikey',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountCreatedApikey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\AccountRc',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation accountRotateApikeyAsync
     *
     * Rotate an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRotateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRotateApikeyAsync(
        string $id,
        string $contentType = self::contentTypes['accountRotateApikey'][0]
    ): PromiseInterface
    {
        return $this->accountRotateApikeyAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation accountRotateApikeyAsyncWithHttpInfo
     *
     * Rotate an API key
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRotateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function accountRotateApikeyAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['accountRotateApikey'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\AccountCreatedApikey';
        $request = $this->accountRotateApikeyRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'accountRotateApikey'
     *
     * @param  string $id The key&#39;s id, as returned by the list endpoint. Never the key itself. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['accountRotateApikey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function accountRotateApikeyRequest(
        string $id,
        string $contentType = self::contentTypes['accountRotateApikey'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling accountRotateApikey'
            );
        }

        $resourcePath = '/api/v1/account/apikeys/{id}/rotate';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
