<?php
/**
 * AuthorizationApi
 * PHP version 8.1
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VPNDetection API
 *
 * The VPNDetection API: classify any IP address, and download the databases behind the answers.  See https://docs.vpndetection.io for guides and https://github.com/vpndetection-io for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.18
 * Contact: support@vpndetection.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VPNDetection\Internal\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use VPNDetection\Internal\ApiException;
use VPNDetection\Internal\Configuration;
use VPNDetection\Internal\HeaderSelector;
use VPNDetection\Internal\ObjectSerializer;

/**
 * AuthorizationApi Class Doc Comment
 *
 * @internal Not part of the public API; `VPNDetection\Client::$oauth` is.
 * @deprecated Since 4.2.0, and removed in the next major. Use `VPNDetection\Client::$oauth`.
 *
 * @package  VPNDetection\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthorizationApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'oauthAuthorize' => [
            'application/json',
        ],
        'oauthDeviceAuthorization' => [
            'application/x-www-form-urlencoded',
        ],
        'oauthMetadata' => [
            'application/json',
        ],
        'oauthRevoke' => [
            'application/x-www-form-urlencoded',
        ],
        'oauthToken' => [
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation oauthAuthorize
     *
     * Authorize
     *
     * @param  string $client_id client_id (required)
     * @param  string $redirect_uri redirect_uri (required)
     * @param  string $response_type response_type (required)
     * @param  string $code_challenge code_challenge (required)
     * @param  string|null $code_challenge_method S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
     * @param  string|null $scope scope (optional)
     * @param  string|null $state Returned unchanged. Use it to bind the response to your request. (optional)
     * @param  string|null $resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthAuthorize'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function oauthAuthorize(
        string $client_id,
        string $redirect_uri,
        string $response_type,
        string $code_challenge,
        ?string $code_challenge_method = null,
        ?string $scope = null,
        ?string $state = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthAuthorize'][0]
    ): void
    {
        $this->oauthAuthorizeWithHttpInfo($client_id, $redirect_uri, $response_type, $code_challenge, $code_challenge_method, $scope, $state, $resource, $contentType);
    }

    /**
     * Operation oauthAuthorizeWithHttpInfo
     *
     * Authorize
     *
     * @param  string $client_id (required)
     * @param  string $redirect_uri (required)
     * @param  string $response_type (required)
     * @param  string $code_challenge (required)
     * @param  string|null $code_challenge_method S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state Returned unchanged. Use it to bind the response to your request. (optional)
     * @param  string|null $resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthAuthorize'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: null, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function oauthAuthorizeWithHttpInfo(
        string $client_id,
        string $redirect_uri,
        string $response_type,
        string $code_challenge,
        ?string $code_challenge_method = null,
        ?string $scope = null,
        ?string $state = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthAuthorize'][0]
    ): array
    {
        $request = $this->oauthAuthorizeRequest($client_id, $redirect_uri, $response_type, $code_challenge, $code_challenge_method, $scope, $state, $resource, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation oauthAuthorizeAsync
     *
     * Authorize
     *
     * @param  string $client_id (required)
     * @param  string $redirect_uri (required)
     * @param  string $response_type (required)
     * @param  string $code_challenge (required)
     * @param  string|null $code_challenge_method S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state Returned unchanged. Use it to bind the response to your request. (optional)
     * @param  string|null $resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthAuthorize'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthAuthorizeAsync(
        string $client_id,
        string $redirect_uri,
        string $response_type,
        string $code_challenge,
        ?string $code_challenge_method = null,
        ?string $scope = null,
        ?string $state = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthAuthorize'][0]
    ): PromiseInterface
    {
        return $this->oauthAuthorizeAsyncWithHttpInfo($client_id, $redirect_uri, $response_type, $code_challenge, $code_challenge_method, $scope, $state, $resource, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation oauthAuthorizeAsyncWithHttpInfo
     *
     * Authorize
     *
     * @param  string $client_id (required)
     * @param  string $redirect_uri (required)
     * @param  string $response_type (required)
     * @param  string $code_challenge (required)
     * @param  string|null $code_challenge_method S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state Returned unchanged. Use it to bind the response to your request. (optional)
     * @param  string|null $resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthAuthorize'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthAuthorizeAsyncWithHttpInfo(
        string $client_id,
        string $redirect_uri,
        string $response_type,
        string $code_challenge,
        ?string $code_challenge_method = null,
        ?string $scope = null,
        ?string $state = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthAuthorize'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->oauthAuthorizeRequest($client_id, $redirect_uri, $response_type, $code_challenge, $code_challenge_method, $scope, $state, $resource, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'oauthAuthorize'
     *
     * @param  string $client_id (required)
     * @param  string $redirect_uri (required)
     * @param  string $response_type (required)
     * @param  string $code_challenge (required)
     * @param  string|null $code_challenge_method S256 only. &#x60;plain&#x60; is refused rather than downgraded. (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state Returned unchanged. Use it to bind the response to your request. (optional)
     * @param  string|null $resource RFC 8707. What the token is FOR, so it cannot be replayed elsewhere. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthAuthorize'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function oauthAuthorizeRequest(
        string $client_id,
        string $redirect_uri,
        string $response_type,
        string $code_challenge,
        ?string $code_challenge_method = null,
        ?string $scope = null,
        ?string $state = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthAuthorize'][0]
    ): Request
    {
        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $client_id when calling oauthAuthorize'
            );
        }
        // verify the required parameter 'redirect_uri' is set
        if ($redirect_uri === null || (is_array($redirect_uri) && count($redirect_uri) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $redirect_uri when calling oauthAuthorize'
            );
        }
        // verify the required parameter 'response_type' is set
        if ($response_type === null || (is_array($response_type) && count($response_type) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $response_type when calling oauthAuthorize'
            );
        }
        // verify the required parameter 'code_challenge' is set
        if ($code_challenge === null || (is_array($code_challenge) && count($code_challenge) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $code_challenge when calling oauthAuthorize'
            );
        }

        $resourcePath = '/oauth/authorize';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_id,
            'client_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $redirect_uri,
            'redirect_uri', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_type,
            'response_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code_challenge,
            'code_challenge', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code_challenge_method,
            'code_challenge_method', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $scope,
            'scope', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $state,
            'state', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resource,
            'resource', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation oauthDeviceAuthorization
     *
     * Device authorization
     *
     * @param  string $client_id client_id (required)
     * @param  string|null $scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
     * @param  string|null $resource RFC 8707: what the token is for. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthDeviceAuthorization'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\DeviceAuthorization|\VPNDetection\Internal\Model\OauthError
     */
    public function oauthDeviceAuthorization(
        string $client_id,
        ?string $scope = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthDeviceAuthorization'][0]
    ): \VPNDetection\Internal\Model\DeviceAuthorization|\VPNDetection\Internal\Model\OauthError
    {
        list($response) = $this->oauthDeviceAuthorizationWithHttpInfo($client_id, $scope, $resource, $contentType);
        return $response;
    }

    /**
     * Operation oauthDeviceAuthorizationWithHttpInfo
     *
     * Device authorization
     *
     * @param  string $client_id (required)
     * @param  string|null $scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
     * @param  string|null $resource RFC 8707: what the token is for. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthDeviceAuthorization'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\DeviceAuthorization|\VPNDetection\Internal\Model\OauthError, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function oauthDeviceAuthorizationWithHttpInfo(
        string $client_id,
        ?string $scope = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthDeviceAuthorization'][0]
    ): array
    {
        $request = $this->oauthDeviceAuthorizationRequest($client_id, $scope, $resource, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\DeviceAuthorization',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\OauthError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\OauthError',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\DeviceAuthorization',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\DeviceAuthorization',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation oauthDeviceAuthorizationAsync
     *
     * Device authorization
     *
     * @param  string $client_id (required)
     * @param  string|null $scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
     * @param  string|null $resource RFC 8707: what the token is for. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthDeviceAuthorization'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthDeviceAuthorizationAsync(
        string $client_id,
        ?string $scope = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthDeviceAuthorization'][0]
    ): PromiseInterface
    {
        return $this->oauthDeviceAuthorizationAsyncWithHttpInfo($client_id, $scope, $resource, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation oauthDeviceAuthorizationAsyncWithHttpInfo
     *
     * Device authorization
     *
     * @param  string $client_id (required)
     * @param  string|null $scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
     * @param  string|null $resource RFC 8707: what the token is for. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthDeviceAuthorization'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthDeviceAuthorizationAsyncWithHttpInfo(
        string $client_id,
        ?string $scope = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthDeviceAuthorization'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\DeviceAuthorization';
        $request = $this->oauthDeviceAuthorizationRequest($client_id, $scope, $resource, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'oauthDeviceAuthorization'
     *
     * @param  string $client_id (required)
     * @param  string|null $scope Space-delimited. Anything your client is not registered for is dropped rather than refused. (optional)
     * @param  string|null $resource RFC 8707: what the token is for. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthDeviceAuthorization'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function oauthDeviceAuthorizationRequest(
        string $client_id,
        ?string $scope = null,
        ?string $resource = null,
        string $contentType = self::contentTypes['oauthDeviceAuthorization'][0]
    ): Request
    {
        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $client_id when calling oauthDeviceAuthorization'
            );
        }

        $resourcePath = '/oauth/device_authorization';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \VPNDetection\Internal\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'client_id' => $client_id,
            'scope' => $scope,
            'resource' => $resource,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation oauthMetadata
     *
     * Discovery
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthMetadata'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\OauthMetadata
     */
    public function oauthMetadata(
        string $contentType = self::contentTypes['oauthMetadata'][0]
    ): \VPNDetection\Internal\Model\OauthMetadata
    {
        list($response) = $this->oauthMetadataWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation oauthMetadataWithHttpInfo
     *
     * Discovery
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthMetadata'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\OauthMetadata, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function oauthMetadataWithHttpInfo(
        string $contentType = self::contentTypes['oauthMetadata'][0]
    ): array
    {
        $request = $this->oauthMetadataRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\OauthMetadata',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\OauthMetadata',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\OauthMetadata',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation oauthMetadataAsync
     *
     * Discovery
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthMetadata'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthMetadataAsync(
        string $contentType = self::contentTypes['oauthMetadata'][0]
    ): PromiseInterface
    {
        return $this->oauthMetadataAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation oauthMetadataAsyncWithHttpInfo
     *
     * Discovery
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthMetadata'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthMetadataAsyncWithHttpInfo(
        string $contentType = self::contentTypes['oauthMetadata'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\OauthMetadata';
        $request = $this->oauthMetadataRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'oauthMetadata'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthMetadata'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function oauthMetadataRequest(
        string $contentType = self::contentTypes['oauthMetadata'][0]
    ): Request
    {

        $resourcePath = '/.well-known/oauth-authorization-server';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation oauthRevoke
     *
     * Revoke
     *
     * @param  string $token An access token or a refresh token. (required)
     * @param  string|null $client_id Accepted and not checked. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthRevoke'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return object
     */
    public function oauthRevoke(
        string $token,
        ?string $client_id = null,
        string $contentType = self::contentTypes['oauthRevoke'][0]
    ): array
    {
        list($response) = $this->oauthRevokeWithHttpInfo($token, $client_id, $contentType);
        return $response;
    }

    /**
     * Operation oauthRevokeWithHttpInfo
     *
     * Revoke
     *
     * @param  string $token An access token or a refresh token. (required)
     * @param  string|null $client_id Accepted and not checked. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthRevoke'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: object, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function oauthRevokeWithHttpInfo(
        string $token,
        ?string $client_id = null,
        string $contentType = self::contentTypes['oauthRevoke'][0]
    ): array
    {
        $request = $this->oauthRevokeRequest($token, $client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation oauthRevokeAsync
     *
     * Revoke
     *
     * @param  string $token An access token or a refresh token. (required)
     * @param  string|null $client_id Accepted and not checked. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthRevoke'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthRevokeAsync(
        string $token,
        ?string $client_id = null,
        string $contentType = self::contentTypes['oauthRevoke'][0]
    ): PromiseInterface
    {
        return $this->oauthRevokeAsyncWithHttpInfo($token, $client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation oauthRevokeAsyncWithHttpInfo
     *
     * Revoke
     *
     * @param  string $token An access token or a refresh token. (required)
     * @param  string|null $client_id Accepted and not checked. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthRevoke'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthRevokeAsyncWithHttpInfo(
        string $token,
        ?string $client_id = null,
        string $contentType = self::contentTypes['oauthRevoke'][0]
    ): PromiseInterface
    {
        $returnType = 'object';
        $request = $this->oauthRevokeRequest($token, $client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'oauthRevoke'
     *
     * @param  string $token An access token or a refresh token. (required)
     * @param  string|null $client_id Accepted and not checked. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthRevoke'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function oauthRevokeRequest(
        string $token,
        ?string $client_id = null,
        string $contentType = self::contentTypes['oauthRevoke'][0]
    ): Request
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $token when calling oauthRevoke'
            );
        }

        $resourcePath = '/oauth/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \VPNDetection\Internal\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'token' => $token,
            'client_id' => $client_id,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation oauthToken
     *
     * Token
     *
     * @param  string $grant_type &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60;, &#x60;authorization_code&#x60; or &#x60;refresh_token&#x60;. (required)
     * @param  string $client_id client_id (required)
     * @param  string|null $device_code Required by the device code grant. (optional)
     * @param  string|null $code Required by the authorization code grant. (optional)
     * @param  string|null $code_verifier Required by the authorization code grant. (optional)
     * @param  string|null $redirect_uri Authorization code grant: the &#x60;redirect_uri&#x60; the code was issued against, exactly. (optional)
     * @param  string|null $refresh_token Required by the refresh token grant. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthToken'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \VPNDetection\Internal\Model\TokenResponse|\VPNDetection\Internal\Model\OauthError
     */
    public function oauthToken(
        string $grant_type,
        string $client_id,
        ?string $device_code = null,
        ?string $code = null,
        ?string $code_verifier = null,
        ?string $redirect_uri = null,
        ?string $refresh_token = null,
        string $contentType = self::contentTypes['oauthToken'][0]
    ): \VPNDetection\Internal\Model\TokenResponse|\VPNDetection\Internal\Model\OauthError
    {
        list($response) = $this->oauthTokenWithHttpInfo($grant_type, $client_id, $device_code, $code, $code_verifier, $redirect_uri, $refresh_token, $contentType);
        return $response;
    }

    /**
     * Operation oauthTokenWithHttpInfo
     *
     * Token
     *
     * @param  string $grant_type &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60;, &#x60;authorization_code&#x60; or &#x60;refresh_token&#x60;. (required)
     * @param  string $client_id (required)
     * @param  string|null $device_code Required by the device code grant. (optional)
     * @param  string|null $code Required by the authorization code grant. (optional)
     * @param  string|null $code_verifier Required by the authorization code grant. (optional)
     * @param  string|null $redirect_uri Authorization code grant: the &#x60;redirect_uri&#x60; the code was issued against, exactly. (optional)
     * @param  string|null $refresh_token Required by the refresh token grant. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthToken'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \VPNDetection\Internal\Model\TokenResponse|\VPNDetection\Internal\Model\OauthError, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function oauthTokenWithHttpInfo(
        string $grant_type,
        string $client_id,
        ?string $device_code = null,
        ?string $code = null,
        ?string $code_verifier = null,
        ?string $redirect_uri = null,
        ?string $refresh_token = null,
        string $contentType = self::contentTypes['oauthToken'][0]
    ): array
    {
        $request = $this->oauthTokenRequest($grant_type, $client_id, $device_code, $code, $code_verifier, $redirect_uri, $refresh_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\TokenResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\OauthError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\VPNDetection\Internal\Model\OauthError',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\VPNDetection\Internal\Model\TokenResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\TokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\VPNDetection\Internal\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation oauthTokenAsync
     *
     * Token
     *
     * @param  string $grant_type &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60;, &#x60;authorization_code&#x60; or &#x60;refresh_token&#x60;. (required)
     * @param  string $client_id (required)
     * @param  string|null $device_code Required by the device code grant. (optional)
     * @param  string|null $code Required by the authorization code grant. (optional)
     * @param  string|null $code_verifier Required by the authorization code grant. (optional)
     * @param  string|null $redirect_uri Authorization code grant: the &#x60;redirect_uri&#x60; the code was issued against, exactly. (optional)
     * @param  string|null $refresh_token Required by the refresh token grant. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthToken'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthTokenAsync(
        string $grant_type,
        string $client_id,
        ?string $device_code = null,
        ?string $code = null,
        ?string $code_verifier = null,
        ?string $redirect_uri = null,
        ?string $refresh_token = null,
        string $contentType = self::contentTypes['oauthToken'][0]
    ): PromiseInterface
    {
        return $this->oauthTokenAsyncWithHttpInfo($grant_type, $client_id, $device_code, $code, $code_verifier, $redirect_uri, $refresh_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation oauthTokenAsyncWithHttpInfo
     *
     * Token
     *
     * @param  string $grant_type &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60;, &#x60;authorization_code&#x60; or &#x60;refresh_token&#x60;. (required)
     * @param  string $client_id (required)
     * @param  string|null $device_code Required by the device code grant. (optional)
     * @param  string|null $code Required by the authorization code grant. (optional)
     * @param  string|null $code_verifier Required by the authorization code grant. (optional)
     * @param  string|null $redirect_uri Authorization code grant: the &#x60;redirect_uri&#x60; the code was issued against, exactly. (optional)
     * @param  string|null $refresh_token Required by the refresh token grant. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthToken'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function oauthTokenAsyncWithHttpInfo(
        string $grant_type,
        string $client_id,
        ?string $device_code = null,
        ?string $code = null,
        ?string $code_verifier = null,
        ?string $redirect_uri = null,
        ?string $refresh_token = null,
        string $contentType = self::contentTypes['oauthToken'][0]
    ): PromiseInterface
    {
        $returnType = '\VPNDetection\Internal\Model\TokenResponse';
        $request = $this->oauthTokenRequest($grant_type, $client_id, $device_code, $code, $code_verifier, $redirect_uri, $refresh_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'oauthToken'
     *
     * @param  string $grant_type &#x60;urn:ietf:params:oauth:grant-type:device_code&#x60;, &#x60;authorization_code&#x60; or &#x60;refresh_token&#x60;. (required)
     * @param  string $client_id (required)
     * @param  string|null $device_code Required by the device code grant. (optional)
     * @param  string|null $code Required by the authorization code grant. (optional)
     * @param  string|null $code_verifier Required by the authorization code grant. (optional)
     * @param  string|null $redirect_uri Authorization code grant: the &#x60;redirect_uri&#x60; the code was issued against, exactly. (optional)
     * @param  string|null $refresh_token Required by the refresh token grant. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['oauthToken'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function oauthTokenRequest(
        string $grant_type,
        string $client_id,
        ?string $device_code = null,
        ?string $code = null,
        ?string $code_verifier = null,
        ?string $redirect_uri = null,
        ?string $refresh_token = null,
        string $contentType = self::contentTypes['oauthToken'][0]
    ): Request
    {
        // verify the required parameter 'grant_type' is set
        if ($grant_type === null || (is_array($grant_type) && count($grant_type) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $grant_type when calling oauthToken'
            );
        }
        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $client_id when calling oauthToken'
            );
        }

        $resourcePath = '/oauth/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \VPNDetection\Internal\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'grant_type' => $grant_type,
            'client_id' => $client_id,
            'device_code' => $device_code,
            'code' => $code,
            'code_verifier' => $code_verifier,
            'redirect_uri' => $redirect_uri,
            'refresh_token' => $refresh_token,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
